# ReloadKick V1.0 by cluter123
# Support: Message me @ https://bukkit.org/members/cluter123.90802646/


# Kick message to players when the server reloads
message: '&cServer is reloading! Come back in a minute.'