name: ReloadKick
main: me.cluter.customreload.Main
author: cluter123
version: 1.0

commands:
  reloadkick:
    description: Reloads the server and kicks everyone out.

permissions:
  reloadkick.reload:
    description: Gives permission to reload the server.